### ISSUE TITLE
Encoding error reading text_tokenizer.json

### ISSUE THREAD

**Issue by throttlekitty** [Alpha-VLLM/Lumina-mGPT#2]
On launch, I got the following error:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3565933: character maps to <undefined>

For a quick fix, in item_processor.py, line 89, I made this change, but I don't know if it's an issue for other OS however.
`json.load(open("./ckpts/chameleon/tokenizer/text_tokenizer.json", encoding="utf8"))["model"]["vocab"]`

**Comment by ChrisLiu6** [comment]
Thank you for the feedback, we will fix it

**Comment by ChrisLiu6** [comment]
https://github.com/Alpha-VLLM/Lumina-mGPT/commit/87811a3de3a33cbbb118c4cd2d5cf7143acf8e1b
