### ISSUE TITLE
cannot generate 256*256 images?

### ISSUE THREAD

**Issue by zhangzheyu0** [Alpha-VLLM/Lumina-mGPT#20]
Based on line119 of the readme.md, if we want to "generate an image of 256x256 according to the following prompt xxxx.",  it doesn't work, why?

Sincerely look forward for your reply.

**Comment by ChrisLiu6** [comment]
The model was not trained at 256x256. For more details, please refer to the FP-SFT paragraph in our paper.

<img width="421" alt="1724932766545" src="https://github.com/user-attachments/assets/34b74eef-8992-4b73-ab22-6f18f6b33cf7">
