### ISSUE TITLE
How to decode image latents with different resolutions?

### ISSUE THREAD

**Issue by JeremyCJM** [Alpha-VLLM/Lumina-mGPT#24]
A Naive question: how to decode image latents with different resolutions? Since the decode is only trained with specific latent resolutions. Did you split the image with larger resolution with many 512*512 squares to decode separately, and then blend the overlapping area? Could you help locate the code for doing this?

**Comment by ChrisLiu6** [comment]
Even though VAEs are usually trained at fixed resolution, we empirically find that they usually have the ability to process images of different resolutions at high quality, without the need of speicial operations.  Note that from the code implementation perspective, Meta's official Chameleon released has restricted flexible-resolution decoding, so we have slightly modified the vae implementation code to remove the restiction.

**Comment by JeremyCJM** [comment]
Thanks a lot for your prompt reply! Could you explain in more detail and help locate the code of doing this?

**Comment by ChrisLiu6** [comment]
> Thanks a lot for your prompt reply! Could you explain in more detail and help locate the code of doing this?

https://github.com/Alpha-VLLM/Lumina-mGPT/blob/104abe453ec1acca5863698629c4db2111b0b3fc/lumina_mgpt/inference_solver.py#L371
