### ISSUE TITLE
training with lora？

### ISSUE THREAD

**Issue by xiexing0916** [Alpha-VLLM/Lumina-mGPT#30]
Is there a way (lora?)  to train with less memory burden? Full fine-tuning is not trainable at 48G of RAM.

**Comment by ChrisLiu6** [comment]
The released codes do not support lora yet, but it is easy to implement and you can do it by yourself.  You may also implement the `get_trainable_params` method for the model class to only train part of the model parameters.

https://github.com/Alpha-VLLM/Lumina-mGPT/blob/104abe453ec1acca5863698629c4db2111b0b3fc/xllmx/solvers/finetune/finetune.py#L273

The follows issues may be helpful:

https://github.com/Alpha-VLLM/Lumina-mGPT/issues/17
https://github.com/Alpha-VLLM/Lumina-mGPT/issues/18

**Comment by xiexing0916** [comment]
> The released codes do not support lora yet, but it is easy to implement and you can do it by yourself. You may also implement the `get_trainable_params` method for the model class to only train part of the model parameters.
> 
> https://github.com/Alpha-VLLM/Lumina-mGPT/blob/104abe453ec1acca5863698629c4db2111b0b3fc/xllmx/solvers/finetune/finetune.py#L273
> 
> The follows issues may be helpful:
> 
> #17 #18

Thanks for the answer! I would also like to ask how much memory is needed to fine tune all the parameters? I currently can't work with 3 48G A6000.

**Comment by ChrisLiu6** [comment]
> Thanks for the answer! I would also like to ask how much memory is needed to fine tune all the parameters? I currently can't work with 3 48G A6000.

We have not tested on the memory lower bound. 8*A100 * 80G should be enough, but the the lower I have no idea😅.
