### ISSUE TITLE
Improve Hugging Face integration

### ISSUE THREAD

**Issue by NielsRogge** [Alpha-VLLM/Lumina-mGPT#33]
Hi @ChrisLiu6 and team!

Congrats on Lumina-mGPT. 

I'm Niels and work as part of the open-source team at Hugging Face. I discovered your work through Hugging Face's daily papers as yours got featured: https://huggingface.co/papers/2412.05270.
The paper page lets people discuss about your paper and lets them find artifacts about it (your models for instance),
you can also claim the paper as yours which will show up on your public profile at HF.

2 notes:
* would it be possible to add "pipeline_tag: any-to-any" to each of the models' metadata? Similar to here: https://huggingface.co/Alpha-VLLM/Lumina-mGPT-7B-768/discussions/2#6759ccd7e0ec08a39dde2f8a
* would it be possible to add a model card to the following models? 
** https://huggingface.co/Alpha-VLLM/Lumina-mGPT-7B-512
** https://huggingface.co/Alpha-VLLM/Lumina-mGPT-7B-768-Omni
** https://huggingface.co/Alpha-VLLM/Lumina-mGPT-7B-1024
** https://huggingface.co/Alpha-VLLM/Lumina-mGPT-34B-512

Let me know if you need any assistance.

Thanks!

**Comment by ChrisLiu6** [comment]
Hello! Thank you so much for you reminder and assistance. We have merged the PRs you made on HF. Thank you again for your efforts in making our work better.

**Comment by NielsRogge** [comment]
Thanks for quicky merging them! Let us know when you have a next release.

Cheers
