### ISSUE TITLE
Link to 34B model leads to 404 page

### ISSUE THREAD

**Issue by RandomInternetPreson** [Alpha-VLLM/Lumina-mGPT#4]
https://huggingface.co/Alpha-VLLM/Lumina-mGPT-34B-512

Tried accessing the link for the 34B model on the repo site and it is no available on huggingface.

**Comment by gohan2091** [comment]
Same

**Comment by ChrisLiu6** [comment]
It should come within 24 hours. Due to the network problem, the uploading failed several times.

**Comment by ChrisLiu6** [comment]
uploaded
