### ISSUE TITLE
VQGAN models dont exist

### ISSUE THREAD

**Issue by gjnave** [Alpha-VLLM/Lumina-mGPT#5]
- text_tokenizer.json
                - vqgan.yaml
                - vqgan.ckpt
are not in the repo the directory points to

**Comment by Excidos** [comment]
You need to download them seperately from Meta, https://ai.meta.com/resources/models-and-libraries/chameleon-downloads/

I had to get a VM running with Linux to finish the process from the email, just git clone the Chameleon repository and follow the steps.
